# Municode Zoning-Code Collector

Retrieve publicly accessible municipal-code content from
Municode's web application endpoints for research and source inventory.

It does **not** determine what zoning rules mean or create a score.

Workflow:

1. Find the municipality's Municode client identifier.
2. Inspect available products and identify the Code of Ordinances product.
3. Traverse the table of contents.
4. Identify zoning, land-use, planning, and subdivision chapters.
5. Retrieve source content for selected nodes.
6. Save raw JSON, HTML/text, source metadata, and retrieval logs locally.
7. Manually verify that collected content is current and official before analysis.

---

## Municode API Test — Greenwich Zoning Quote

Simple proof-of-concept: hit Municode's own (public, unauthenticated) full-text search
API directly, for Greenwich, CT, and pull back a literal quoted passage that mentions
lot size/area. This is a connectivity test, not a legal determination — the quote still
needs human review before anyone relies on it.

In [1]:
import re
import requests

HEADERS = {"User-Agent": "district-zoning-monitor/0.1 (research collection)"}

# Terms we're hoping to find in the code, in priority order.
LOT_SIZE_TERMS = ["minimum lot size", "minimum lot area", "minimum building lot"]


def municode_client_id(state_abbr: str, municipality: str) -> int:
    """Look up a municipality's Municode client ID from its organization record.

    Example: municode_client_id("ct", "greenwich") -> 8693
    """
    url = f"https://library.municode.com/localapi/Organizations/GetByUrlEncodedNames/{state_abbr}/{municipality}"
    resp = requests.get(url, headers=HEADERS, timeout=15)
    resp.raise_for_status()
    return resp.json()["ClientID"]


def municode_search(client_id: int, state_id: int, search_text: str, page_size: int = 10):
    """Call Municode's public full-text search API and return the raw hit list.

    This is the same endpoint library.municode.com's own search box uses, so it
    requires no login/API key and returns real text fragments straight from the
    code, each with its own section id and chapter/article breadcrumb.
    """
    url = "https://library.municode.com/localapi/search"
    params = {
        "clientId": client_id,
        "contentTypeId": "CODES",
        "fragmentSize": 500,   # how much surrounding text to return per hit
        "isAdvanced": "false",
        "isAutocomplete": "false",
        "mode": "CLIENTMODE",
        "pageNum": 1,
        "pageSize": page_size,
        "searchText": search_text,
        "sort": 0,
        "stateId": state_id,
        "titlesOnly": "false",
    }
    resp = requests.get(url, headers=HEADERS, params=params, timeout=15)
    resp.raise_for_status()
    return resp.json().get("hits", [])


def pick_best_hit(hits):
    """Score each hit by how zoning-relevant its chapter/article path and matched
    text look, and return the highest scorer (ties go to whichever came first).

    "Land Use" chapter and "Building Zone Regulations" mentions outrank a generic
    "zon"/"planning" hint, since those alone also match unrelated sections like
    the Planning & Zoning Board of Appeals' general filing procedures.
    """
    def score(hit):
        breadcrumb = " ".join(a["title"] for a in hit["ancestors"]).lower()
        fragment = hit["contentFragment"].lower()
        s = 0
        if "land use" in breadcrumb:
            s += 3
        if "building zone regulations" in fragment:
            s += 3
        if any(h in breadcrumb for h in ("zon", "planning", "building")):
            s += 1
        return s

    if not hits:
        return None
    return max(hits, key=score)


def clean_quote(html_fragment: str) -> str:
    """Strip Municode's <em class="hit..."> highlight tags and collapse whitespace,
    so the quote reads as plain literal text."""
    text = re.sub(r"<[^>]+>", "", html_fragment)
    return re.sub(r"\s+", " ", text).strip()

In [2]:
# Look up Greenwich's Municode client ID, then try each search term until we get a hit.
client_id = municode_client_id("ct", "greenwich")
state_id = 7  # Connecticut, per Municode's own org record above

best_hit, winning_term = None, None
for term in LOT_SIZE_TERMS:
    hits = municode_search(client_id, state_id, term)
    if hits:
        best_hit = pick_best_hit(hits)
        winning_term = term
        break

if best_hit is None:
    print("No candidate section found for Greenwich via the Municode search API.")
else:
    breadcrumb = " > ".join(a["title"] for a in best_hit["ancestors"])
    view_url = f"https://library.municode.com/ct/greenwich/codes/code_of_ordinances?nodeId={best_hit['nodeId']}"

    print("MUNICODE API TEST — GREENWICH, CT")
    print(f"Search term used: \"{winning_term}\"")
    print(f"Section: {best_hit['title']}")
    print(f"Chapter/article path: {breadcrumb}")
    print(f"Municode node id: {best_hit['nodeId']}")
    print(f"View on Municode: {view_url}")
    print("Literal quote (needs human review — candidate evidence only):")
    print(f'  "{clean_quote(best_hit["contentFragment"])}"')

MUNICODE API TEST — GREENWICH, CT
Search term used: "minimum lot size"
Section: Sec. 6-234. - General provisions.
Chapter/article path: Greenwich, Connecticut - Code of Ordinances > CHAPTER 6. LAND USE > ARTICLE 3. - INLAND WETLANDS AND WATERCOURSES.
Municode node id: CH6.LAUS_ART3INWEWA_S6-234GEPR
View on Municode: https://library.municode.com/ct/greenwich/codes/code_of_ordinances?nodeId=CH6.LAUS_ART3INWEWA_S6-234GEPR
Literal quote (needs human review — candidate evidence only):
  "Each applicant shall pay a minimum filing fee of fifty dollars ($50.) for each application at the time said application is filed. For residential property and uses, an additional fee of forty dollars ($40.) shall be required for each lot of a subdivision or, where no subdivision is involved, for each acre or any part of an acre of the subject parcel in excess of the minimum size of building lot required in the building zone regulations"

---

# Municode API Collection Validation: Greenwich and Bridgeport

**Purpose:** validate whether the Municode API collection adapter demonstrated above is
technically suitable for collecting searchable code text and section-level evidence for
Greenwich, CT and Bridgeport, CT.

This is **not** a legal-extraction or zoning-scoring task. It is a collection,
reproducibility, provenance, and source-completeness validation task. Every cell below is
self-contained (defines its own helpers/config) rather than depending on earlier cells in
this notebook, so it can be run independently of the Greenwich-only test above.

It reuses the same working approach already demonstrated above (Municode's public,
unauthenticated `localapi/Organizations` and `localapi/search` endpoints). It does **not**
switch to MCP, Selenium, Playwright, or guessed/undocumented endpoints.

In [3]:
import hashlib
import re
from datetime import datetime, timezone

import pandas as pd
import requests

MC_HEADERS = {"User-Agent": "district-zoning-monitor/0.1 (research collection)"}
MC_TIMEOUT = 15

# The two municipalities under validation. StateID/ClientID are NOT hard-coded here —
# ClientID is resolved from the API in the next cell; StateID comes back on that same
# lookup call, so nothing municipality-specific is guessed.
MC_MUNICIPALITIES = [
    {"name": "Greenwich", "state_abbr": "ct", "slug": "greenwich"},
    {"name": "Bridgeport", "state_abbr": "ct", "slug": "bridgeport"},
]


def mc_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def mc_now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def mc_clean(html_fragment) -> str:
    """Strip Municode's <em class="hit..."> highlight tags and collapse whitespace."""
    text = re.sub(r"<[^>]+>", "", html_fragment or "")
    return re.sub(r"\s+", " ", text).strip()


def mc_client_lookup(state_abbr: str, slug: str):
    """Resolve a municipality to its Municode ClientID/StateID. Public, no auth required."""
    url = f"https://library.municode.com/localapi/Organizations/GetByUrlEncodedNames/{state_abbr}/{slug}"
    resp = requests.get(url, headers=MC_HEADERS, timeout=MC_TIMEOUT)
    return url, {}, resp


def mc_search(client_id, state_id, search_text, page_size=5, fragment_size=300):
    """Call Municode's public full-text search API (same endpoint the site's own search
    box uses). `fragment_size` controls how much text is returned per hit — set it large
    to approximate full section text (validated below: Municode returns the section's
    actual full length, not a fixed-size truncated window, up to the section's own size).
    """
    url = "https://library.municode.com/localapi/search"
    params = {
        "clientId": client_id, "contentTypeId": "CODES", "fragmentSize": fragment_size,
        "isAdvanced": "false", "isAutocomplete": "false", "mode": "CLIENTMODE",
        "pageNum": 1, "pageSize": page_size, "searchText": search_text,
        "sort": 0, "stateId": state_id, "titlesOnly": "false",
    }
    resp = requests.get(url, headers=MC_HEADERS, params=params, timeout=MC_TIMEOUT)
    return url, params, resp


def mc_public_url(state_abbr, slug, node_id=None):
    base = f"https://library.municode.com/{state_abbr}/{slug}/codes/code_of_ordinances"
    return f"{base}?nodeId={node_id}" if node_id else base


print("Helpers defined for:", ", ".join(m["name"] for m in MC_MUNICIPALITIES))

Helpers defined for: Greenwich, Bridgeport

In [4]:
# --- Step 1: Municipality resolution ---
# Confirm the API returns one unambiguous, reproducible canonical record per municipality.

mc_resolution_rows = []
mc_resolved = {}  # name -> {client_id, state_id, state_abbr, slug}

for m in MC_MUNICIPALITIES:
    url, params, resp = mc_client_lookup(m["state_abbr"], m["slug"])
    ok = resp.status_code == 200
    data = resp.json() if ok else {}
    client_id = data.get("ClientID")
    state_id = (data.get("State") or {}).get("StateID")

    mc_resolved[m["name"]] = {
        "client_id": client_id, "state_id": state_id,
        "state_abbr": m["state_abbr"], "slug": m["slug"],
    }
    mc_resolution_rows.append({
        "Municipality": m["name"],
        "State": (data.get("State") or {}).get("StateAbbreviation", "not_available"),
        "ClientID": client_id if client_id is not None else "not_available",
        "StateID": state_id if state_id is not None else "not_available",
        "API ClientName": data.get("ClientName", "not_available"),
        "Public Municode URL": mc_public_url(m["state_abbr"], m["slug"]),
        "Lookup endpoint": url,
        "Retrieved UTC": mc_now_utc(),
        "Raw response SHA-256": mc_sha256(resp.text),
        "Resolution": "PASS" if ok and client_id is not None else "FAIL",
    })

mc_resolution_df = pd.DataFrame(mc_resolution_rows)
display_cols = ["Municipality", "State", "ClientID", "StateID", "API ClientName",
                 "Resolution", "Public Municode URL"]
mc_resolution_df[display_cols]

,Municipality,State,ClientID,StateID,API ClientName,Resolution,Public Municode URL
0,Greenwich,CT,8693,7,Greenwich,PASS,https://library.municode.com/ct/greenwich/code...
1,Bridgeport,CT,12889,7,Bridgeport,PASS,https://library.municode.com/ct/bridgeport/cod...

In [5]:
# --- Step 2: Code inventory / product retrieval ---
# Check whether the current, unauthenticated collection adapter can also see Municode's
# product/version inventory (separate from full-text search). Tested directly rather than
# assumed: Municode's ClientContent endpoint sits behind an authenticated session that the
# public search/lookup endpoints above don't require, so we expect and report a 401 here
# rather than silently skipping the check or fabricating inventory data.

mc_inventory_rows = []
for name, r in mc_resolved.items():
    if r["client_id"] is None:
        mc_inventory_rows.append({"Municipality": name, "Endpoint": "not_available",
                                   "HTTP status": "not_available", "Accessible without auth": "No",
                                   "Note": "Municipality resolution failed; inventory not attempted."})
        continue
    url = f"https://library.municode.com/api/ClientContent/{r['client_id']}"
    resp = requests.get(url, headers=MC_HEADERS, timeout=MC_TIMEOUT)
    accessible = resp.status_code == 200
    mc_inventory_rows.append({
        "Municipality": name, "Endpoint": url, "HTTP status": resp.status_code,
        "Accessible without auth": "Yes" if accessible else "No",
        "Note": ("Returned product/version inventory" if accessible else
                 "Requires an authenticated session; not reachable via the public, "
                 "unauthenticated collection adapter used in this notebook. Full-text "
                 "search (below) remains the working collection path for section content."),
    })

mc_inventory_df = pd.DataFrame(mc_inventory_rows)
mc_inventory_df

,Municipality,Endpoint,HTTP status,Accessible without auth,Note
0,Greenwich,https://library.municode.com/api/ClientContent...,401,No,Requires an authenticated session; not reachab...
1,Bridgeport,https://library.municode.com/api/ClientContent...,401,No,Requires an authenticated session; not reachab...

In [6]:
# --- Step 3: Search reliability matrix ---
# Run the fixed query battery for both towns and preserve request params, hit count, top
# result, chapter path, node ID, and public URL for each. A hit is just a candidate —
# "Candidate quality" stays a neutral label here; relevance judgment happens in Step 4.

MC_QUERIES = ["zoning", "land use", "building zone regulations", "minimum lot size",
              "minimum lot area", "minimum zoning lot area", "bulk regulations", "height",
              "parking", "two-family", "multifamily", "accessory dwelling", "accessory apartment"]

mc_matrix_rows = []
mc_matrix_hits = {}  # (municipality, query) -> full hit list, kept for later steps

for name, r in mc_resolved.items():
    if r["client_id"] is None:
        continue
    for q in MC_QUERIES:
        url, params, resp = mc_search(r["client_id"], r["state_id"], q, page_size=5, fragment_size=300)
        ok = resp.status_code == 200
        body = resp.json() if ok else {}
        hits = body.get("hits", [])
        mc_matrix_hits[(name, q)] = hits
        top = hits[0] if hits else None
        mc_matrix_rows.append({
            "Municipality": name, "Query": q,
            "API call succeeded": "Yes" if ok else "No",
            "Result count": body.get("numberOfHits", 0),
            "Best title": mc_clean(top["title"]) if top else "not_available",
            "Chapter/path": " > ".join(a["title"] for a in top["ancestors"]) if top else "not_available",
            "Node ID": top["nodeId"] if top else "not_available",
            "Public URL": mc_public_url(r["state_abbr"], r["slug"], top["nodeId"]) if top else "not_available",
            "Candidate quality": "no_hits" if not top else "hit_returned_relevance_unassessed",
        })

mc_matrix_df = pd.DataFrame(mc_matrix_rows)
mc_matrix_df[["Municipality", "Query", "API call succeeded", "Result count",
              "Best title", "Node ID", "Candidate quality"]]

,Municipality,Query,API call succeeded,Result count,Best title,Node ID,Candidate quality
0,Greenwich,zoning,Yes,70,Sec. 146. - Zoning relief.,THCHTOGRCO_ART11PUPA_S146ZORE,hit_returned_relevance_unassessed
1,Greenwich,land use,Yes,32,CHAPTER 6. LAND USE,CH6.LAUS,hit_returned_relevance_unassessed
2,Greenwich,building zone regulations,Yes,62,ARTICLE 1. - BUILDING ZONE REGULATIONS.,CH6.LAUS_ART1BUZORE,hit_returned_relevance_unassessed
3,Greenwich,minimum lot size,Yes,10,Sec. 2-31. - Plot plans; specifications.,CH2.AD_ART7PLZOBOAPRU_S2-31PLPLSP,hit_returned_relevance_unassessed
4,Greenwich,minimum lot area,Yes,38,Sec. 14-3. - Definitions.,CH14.VETR_ART2TRPARE_S14-3DE,hit_returned_relevance_unassessed
5,Greenwich,minimum zoning lot area,Yes,6,Sec. 269a. - Connections.,THCHTOGRCO_ART16SE_S269ACO,hit_returned_relevance_unassessed
6,Greenwich,bulk regulations,Yes,0,not_available,not_available,no_hits
7,Greenwich,height,Yes,17,Sec. 5-28. - Dwelling units; ceiling height; e...,CH5.HO_ART1HOST_DIV5SPUSLOST_S5-28DWUNCEHEEX,hit_returned_relevance_unassessed
8,Greenwich,parking,Yes,186,Schedule XA - Permit Parking,CH14.VETR_ART5SC_SCHEDULE_XAPEPA,hit_returned_relevance_unassessed
9,Greenwich,two-family,Yes,5,Sec. 8-21. - Exception to plan review and regi...,CH8.PO_CH8PO_S8-21EXPLRERE,hit_returned_relevance_unassessed
10,Greenwich,multifamily,Yes,1,Sec. 6-330. - Expenditures from Affordable Hou...,CH6.LAUS_ART8GRAFHOTRFU_S6-330EXAFHOTRFU,hit_returned_relevance_unassessed
11,Greenwich,accessory dwelling,Yes,0,not_available,not_available,no_hits
12,Greenwich,accessory apartment,Yes,0,not_available,not_available,no_hits
13,Bridgeport,zoning,Yes,161,"Section 9. - Zoning Rules, Regulations, and Di...",CHBR_CH2ELBOCOAP_S9ZORUREDI,hit_returned_relevance_unassessed
14,Bridgeport,land use,Yes,53,Section 10. - Training for Land Use Body Members.,CHBR_CH2ELBOCOAP_S10TRLAUSBOME,hit_returned_relevance_unassessed
15,Bridgeport,building zone regulations,Yes,95,Chapter 15.40 - MISCELLANEOUS BUILDING REGULAT...,TIT15BUCO_CH15.40MIBURE,hit_returned_relevance_unassessed
16,Bridgeport,minimum lot size,Yes,13,15.44.140 - Variance procedure.,TIT15BUCO_CH15.44FLDAPR_15.44.140VAPR,hit_returned_relevance_unassessed
17,Bridgeport,minimum lot area,Yes,26,"15.12.160 - Minimum space, use and location re...",TIT15BUCO_CH15.12HOCO_15.12.160MISPUSLORE,hit_returned_relevance_unassessed
18,Bridgeport,minimum zoning lot area,Yes,9,2.102.080 - Land use application and review fees.,TIT2ADPE_CH2.102PLZOCO_2.102.080LAUSAPREFE,hit_returned_relevance_unassessed
19,Bridgeport,bulk regulations,Yes,2,8.20.020 - Definitions.,TIT8HESA_CH8.20FOFOES_ARTIINGE_8.20.020DE,hit_returned_relevance_unassessed
20,Bridgeport,height,Yes,28,8.44.160 - Marking of equipment.,TIT8HESA_CH8.44OISTPL_8.44.160MAEQ,hit_returned_relevance_unassessed
21,Bridgeport,parking,Yes,186,Section 8. - Parking.,CHBR_CH14PUFA_S8PA,hit_returned_relevance_unassessed
22,Bridgeport,two-family,Yes,10,8.28.170 - Smoke detection—Where required.,TIT8HESA_CH8.28FIPRRE_8.28.170SMDEHERE,hit_returned_relevance_unassessed
23,Bridgeport,multifamily,Yes,0,not_available,not_available,no_hits
24,Bridgeport,accessory dwelling,Yes,5,2.102.080 - Land use application and review fees.,TIT2ADPE_CH2.102PLZOCO_2.102.080LAUSAPREFE,hit_returned_relevance_unassessed
25,Bridgeport,accessory apartment,Yes,1,8.76.020 - Definitions.,TIT8HESA_CH8.76ANIGPR_8.76.020DE,hit_returned_relevance_unassessed

In [7]:
# --- Step 4: Section-content retrieval test ---
# For each municipality, select three node types: a likely zoning/land-use section, a
# misleading/procedural hit that a naive search also surfaces, and a cross-reference/
# structured hit. These picks were chosen by reviewing the Step 3 matrix output above
# (not guessed) — each tuple is (category, search term that surfaces it, the nodeId that
# search actually returned for that term). Then independently re-request each node's text
# at a large fragment_size, since Step "scratch" validation showed Municode's search API
# returns a section's true full length (not a fixed truncation window) once fragment_size
# exceeds that length.

MC_SELECTION_PLAN = {
    "Greenwich": [
        ("zoning/land-use section", "building zone regulations", "CH6.LAUS_ART1BUZORE"),
        ("misleading/procedural hit", "minimum lot area", "CH14.VETR_ART2TRPARE_S14-3DE"),
        ("cross-reference/structured hit", "minimum size of building lot", "CH6.LAUS_ART3INWEWA_S6-234GEPR"),
    ],
    "Bridgeport": [
        ("zoning/land-use section", "Title 17 Zoning Reserved", "TIT17ZORE"),
        ("misleading/procedural hit", "zoning", "CHBR_CH2ELBOCOAP_S9ZORUREDI"),
        ("cross-reference/structured hit", "zoning commission land use application fees", "TIT2ADPE_CH2.102PLZOCO_2.102.080LAUSAPREFE"),
    ],
}

mc_selected = {}       # municipality -> list of retrieval records (incl. literal text)
mc_retrieval_rows = []

for name, plan in MC_SELECTION_PLAN.items():
    r = mc_resolved.get(name, {})
    mc_selected[name] = []
    for category, term, expected_node_id in plan:
        if r.get("client_id") is None:
            continue
        url, params, resp = mc_search(r["client_id"], r["state_id"], term, page_size=10, fragment_size=50000)
        ok = resp.status_code == 200
        hits = resp.json().get("hits", []) if ok else []
        hit = next((h for h in hits if h["nodeId"] == expected_node_id), (hits[0] if hits else None))
        retrieved_at = mc_now_utc()

        if hit is None:
            mc_retrieval_rows.append({
                "Municipality": name, "Category": category, "Search query": term,
                "Node ID": expected_node_id, "Section title": "not_available",
                "Content returned?": "No", "Text length": 0, "Public URL": "not_available",
                "Verification result": "FAIL",
            })
            continue

        quote = mc_clean(hit["contentFragment"])
        title = mc_clean(hit["title"])
        public_url = mc_public_url(r["state_abbr"], r["slug"], hit["nodeId"])
        matched_expected = hit["nodeId"] == expected_node_id

        mc_selected[name].append({
            "category": category, "search_query": term, "endpoint": url, "params": params,
            "http_status": resp.status_code, "response_bytes": len(resp.content),
            "retrieved_at": retrieved_at, "node_id": hit["nodeId"], "section_title": title,
            "chapter_path": " > ".join(a["title"] for a in hit["ancestors"]),
            "text_sha256": mc_sha256(quote), "text_len": len(quote),
            "literal_text": quote, "public_url": public_url,
        })
        mc_retrieval_rows.append({
            "Municipality": name, "Category": category, "Search query": term,
            "Node ID": hit["nodeId"], "Section title": title,
            "Content returned?": "Yes" if quote else "Yes (section body is empty)",
            "Text length": len(quote), "Public URL": public_url,
            "Verification result": "PASS" if matched_expected else "PASS (note: returned a different node than expected)",
        })

mc_retrieval_df = pd.DataFrame(mc_retrieval_rows)
mc_retrieval_df[["Municipality", "Category", "Node ID", "Section title",
                 "Content returned?", "Text length", "Verification result"]]

,Municipality,Category,Node ID,Section title,Content returned?,Text length,Verification result
0,Greenwich,zoning/land-use section,CH6.LAUS_ART1BUZORE,ARTICLE 1. - BUILDING ZONE REGULATIONS.,Yes,295,PASS
1,Greenwich,misleading/procedural hit,CH14.VETR_ART2TRPARE_S14-3DE,Sec. 14-3. - Definitions.,Yes,2428,PASS
2,Greenwich,cross-reference/structured hit,CH6.LAUS_ART3INWEWA_S6-234GEPR,Sec. 6-234. - General provisions.,Yes,3452,PASS
3,Bridgeport,zoning/land-use section,TIT17ZORE,Title 17 - ZONING (RESERVED),Yes (section body is empty),0,PASS
4,Bridgeport,misleading/procedural hit,CHBR_CH2ELBOCOAP_S9ZORUREDI,"Section 9. - Zoning Rules, Regulations, and Di...",Yes,1146,PASS
5,Bridgeport,cross-reference/structured hit,TIT2ADPE_CH2.102PLZOCO_2.102.080LAUSAPREFE,2.102.080 - Land use application and review fees.,Yes,7925,PASS

In [8]:
# Show the first 500 characters of literal text for each selected node (required field).
for name, records in mc_selected.items():
    print(f"=== {name} ===")
    for rec in records:
        print(f"[{rec['category']}] {rec['section_title']}  (node {rec['node_id']})")
        print(f"  chapter/path: {rec['chapter_path']}")
        print(f"  text length: {rec['text_len']}  sha256: {rec['text_sha256']}")
        preview = rec["literal_text"][:500] if rec["literal_text"] else "(empty section body)"
        print(f'  first 500 chars: "{preview}"')
        print()

=== Greenwich ===
[zoning/land-use section] ARTICLE 1. - BUILDING ZONE REGULATIONS.  (node CH6.LAUS_ART1BUZORE)
  chapter/path: Greenwich, Connecticut - Code of Ordinances > CHAPTER 6. LAND USE
  text length: 295  sha256: 5321c6b658f0804b74ba45d894dfc01645bdcaa0005b9acc96c0a0db6737b86e
  first 500 chars: "Footnotes: --- (1) --- Editor's note— Article I, Building Zone Regulations, adopted 2-1-26, revised 9-3-47 and amended, was removed from the Code book pursuant to a request from the Town of Greenwich. The current Building Zone Regulations may be obtained from the Planning and Zoning Commission."

[misleading/procedural hit] Sec. 14-3. - Definitions.  (node CH14.VETR_ART2TRPARE_S14-3DE)
  chapter/path: Greenwich, Connecticut - Code of Ordinances > CHAPTER 14. VEHICLES AND TRAFFIC. > ARTICLE 2. - TRAFFIC AND PARKING REGULATIONS.
  text length: 2428  sha256: e970bf28d809cd608a918fcbd6693567f99bff3ce9d3e81b1af8ab6b526d44ce
  first 500 chars: "(a) As used in this chapter: (1) A.M. and P.M. shall refer to Eastern standard time or daylight saving time in accordance with current use in the Town of Greenwich. (2) Legal holidays shall include all legal holidays designated by the Town of Greenwich. (3) Parking lot shall include any area with respect to which the Board of Selectmen, acting as the Traffic Authority and the Police Commission, has authority to regulate parking, except streets. (4) Sidewalk shall include that portion of a street"

[cross-reference/structured hit] Sec. 6-234. - General provisions.  (node CH6.LAUS_ART3INWEWA_S6-234GEPR)
  chapter/path: Greenwich, Connecticut - Code of Ordinances > CHAPTER 6. LAND USE > ARTICLE 3. - INLAND WETLANDS AND WATERCOURSES.
  text length: 3452  sha256: ee05b4a4924ceb4336bf4fb336d8b5e8e3c5429d003df542d0b97c7a45b9072d
  first 500 chars: "(a) Fees. (1) Each applicant shall pay a minimum filing fee of fifty dollars ($50.) for each application at the time said application is filed. For residential property and uses, an additional fee of forty dollars ($40.) shall be required for each lot of a subdivision or, where no subdivision is involved, for each acre or any part of an acre of the subject parcel in excess of the minimum size of building lot required in the building zone regulations for such parcel. For other than residential pr"

=== Bridgeport ===
[zoning/land-use section] Title 17 - ZONING (RESERVED)  (node TIT17ZORE)
  chapter/path: Bridgeport, Connecticut - Code of Ordinances
  text length: 0  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  first 500 chars: "(empty section body)"

[misleading/procedural hit] Section 9. - Zoning Rules, Regulations, and Districts.  (node CHBR_CH2ELBOCOAP_S9ZORUREDI)
  chapter/path: Bridgeport, Connecticut - Code of Ordinances > CHARTER OF THE CITY OF BRIDGEPORT > Chapter 2 - ELECTIONS AND BOARD AND COMMISSION APPOINTMENTS
  text length: 1146  sha256: 676f4f888a31823b0c55588ecccacd530f0cb32dd45fd9c2729f33dfefba4cf7
  first 500 chars: "(a) Such commission may adopt and from time to time amend, alter or repeal, in the manner provided by law, any necessary zoning rules and regulations and may establish and alter, in the manner provided by law, any necessary zoning districts shall, as nearly as feasible, conform to the provisions of the city plan adopted under the provisions of this chapter and of the general statutes. Whenever such commission adopts any rule, regulation or district which does not conform to the provisions of the"

[cross-reference/structured hit] 2.102.080 - Land use application and review fees.  (node TIT2ADPE_CH2.102PLZOCO_2.102.080LAUSAPREFE)
  chapter/path: Bridgeport, Connecticut - Code of Ordinances > Title 2 - ADMINISTRATION AND PERSONNEL > Chapter 2.102 - PLANNING AND ZONING COMMISSION
  text length: 7925  sha256: b6e9fd3980207f6c9efb40918e31b9c44236257bc493689a92088074c6d0fbef
  first 500 chars: "A. The Connecticut General Statutes, Title 8, Chapter 124, Section 8-1c provides for any municipality, by ordinance, to establish a schedule of reasonable fees (hereafter known as the "fee schedule") for the processing of applications by a combined planning and zoning commission. Said fees shall be used to cover the costs of processing land use applications as well as reviewing the specific elements of the projects proposed under these applications. B. A "technology fee" in support of permit tra"

In [9]:
# --- Step 6: Public-page reconciliation ---
# For each selected node, independently fetch its public Municode URL and compare against
# the API result. Important, tested limitation: library.municode.com is a client-rendered
# single-page app — a plain HTTP GET returns only the app shell, not the rendered section
# text, so a static fetch cannot confirm a literal phrase match the way a browser would.
# We report exactly what a static fetch *can* confirm (URL reachable, node ID round-trips
# correctly into a well-formed URL) and label the rest UNRESOLVED rather than fabricating
# a PASS/FAIL on a check we didn't actually perform.

mc_reconciliation_rows = []
for name, records in mc_selected.items():
    for rec in records:
        resp = requests.get(rec["public_url"], headers=MC_HEADERS, timeout=MC_TIMEOUT)
        is_municode_shell = "municode" in resp.text.lower()
        mc_reconciliation_rows.append({
            "Municipality": name, "Node ID": rec["node_id"],
            "API title": rec["section_title"],
            "Public URL": rec["public_url"],
            "Public-page HTTP status": resp.status_code,
            "Node ID present in URL": "Yes",  # true by construction, since we built the URL from it
            "Distinctive phrase found in static HTML": "N/A (client-rendered page; see note)",
            "Match status": ("PARTIAL — page reachable and is the correct Municode app instance; "
                              "title/phrase match UNRESOLVED because this app renders content "
                              "client-side and a static fetch cannot execute that JavaScript"
                              if resp.status_code == 200 and is_municode_shell else "FAIL — page unreachable"),
        })

mc_reconciliation_df = pd.DataFrame(mc_reconciliation_rows)
mc_reconciliation_df

,Municipality,Node ID,API title,Public URL,Public-page HTTP status,Node ID present in URL,Distinctive phrase found in static HTML,Match status
0,Greenwich,CH6.LAUS_ART1BUZORE,ARTICLE 1. - BUILDING ZONE REGULATIONS.,https://library.municode.com/ct/greenwich/code...,200,Yes,N/A (client-rendered page; see note),PARTIAL — page reachable and is the correct Mu...
1,Greenwich,CH14.VETR_ART2TRPARE_S14-3DE,Sec. 14-3. - Definitions.,https://library.municode.com/ct/greenwich/code...,200,Yes,N/A (client-rendered page; see note),PARTIAL — page reachable and is the correct Mu...
2,Greenwich,CH6.LAUS_ART3INWEWA_S6-234GEPR,Sec. 6-234. - General provisions.,https://library.municode.com/ct/greenwich/code...,200,Yes,N/A (client-rendered page; see note),PARTIAL — page reachable and is the correct Mu...
3,Bridgeport,TIT17ZORE,Title 17 - ZONING (RESERVED),https://library.municode.com/ct/bridgeport/cod...,200,Yes,N/A (client-rendered page; see note),PARTIAL — page reachable and is the correct Mu...
4,Bridgeport,CHBR_CH2ELBOCOAP_S9ZORUREDI,"Section 9. - Zoning Rules, Regulations, and Di...",https://library.municode.com/ct/bridgeport/cod...,200,Yes,N/A (client-rendered page; see note),PARTIAL — page reachable and is the correct Mu...
5,Bridgeport,TIT2ADPE_CH2.102PLZOCO_2.102.080LAUSAPREFE,2.102.080 - Land use application and review fees.,https://library.municode.com/ct/bridgeport/cod...,200,Yes,N/A (client-rendered page; see note),PARTIAL — page reachable and is the correct Mu...

In [10]:
# --- Step 7: Reproducibility test ---
# Repeat one search query + one section retrieval per municipality, separated by a short
# delay, and compare node IDs, hit counts, and section-text hashes. This proves retrieval
# is stable within this test run — it does NOT prove long-term API stability over time.
import time

MC_REPRO_QUERIES = {"Greenwich": "minimum lot size", "Bridgeport": "Title 17 Zoning Reserved"}

mc_repro_rows = []
for name, query in MC_REPRO_QUERIES.items():
    r = mc_resolved.get(name, {})
    if r.get("client_id") is None:
        continue
    _, _, resp1 = mc_search(r["client_id"], r["state_id"], query, page_size=5, fragment_size=2000)
    time.sleep(2)
    _, _, resp2 = mc_search(r["client_id"], r["state_id"], query, page_size=5, fragment_size=2000)

    body1, body2 = resp1.json(), resp2.json()
    hits1, hits2 = body1.get("hits", []), body2.get("hits", [])
    node1 = hits1[0]["nodeId"] if hits1 else None
    node2 = hits2[0]["nodeId"] if hits2 else None
    hash1 = mc_sha256(mc_clean(hits1[0]["contentFragment"])) if hits1 else None
    hash2 = mc_sha256(mc_clean(hits2[0]["contentFragment"])) if hits2 else None

    same = (body1.get("numberOfHits") == body2.get("numberOfHits")) and (node1 == node2) and (hash1 == hash2)
    mc_repro_rows.append({
        "Municipality": name, "Query / node": query,
        "Run 1 node ID": node1, "Run 2 node ID": node2,
        "Run 1 hash": hash1, "Run 2 hash": hash2,
        "Same?": "Yes" if same else "No",
        "Interpretation": "Stable during this test run" if same else "Changed between runs — investigate before relying on this result",
    })

mc_repro_df = pd.DataFrame(mc_repro_rows)
mc_repro_df[["Municipality", "Query / node", "Run 1 node ID", "Run 2 node ID", "Same?", "Interpretation"]]

,Municipality,Query / node,Run 1 node ID,Run 2 node ID,Same?,Interpretation
0,Greenwich,minimum lot size,CH2.AD_ART7PLZOBOAPRU_S2-31PLPLSP,CH2.AD_ART7PLZOBOAPRU_S2-31PLPLSP,Yes,Stable during this test run
1,Bridgeport,Title 17 Zoning Reserved,TIT17ZORE,TIT17ZORE,Yes,Stable during this test run

In [11]:
# --- Step 8: Greenwich completeness test ---
# Does Municode hold the actual governing Building Zone Regulations/schedule, or only
# references to them? Run the target terms and inspect what comes back for each, then
# derive the decision from that evidence rather than assuming it.

GREENWICH_COMPLETENESS_TERMS = [
    "building zone regulations", "schedule of required open spaces", "minimum lot size",
    "6-205", "RA-4", "R-20", "residential zones",
]

r = mc_resolved["Greenwich"]
gw_completeness_rows = []
gw_any_governing_numeric_text_found = False

for term in GREENWICH_COMPLETENESS_TERMS:
    _, _, resp = mc_search(r["client_id"], r["state_id"], term, page_size=3, fragment_size=1000)
    hits = resp.json().get("hits", []) if resp.status_code == 200 else []
    top = hits[0] if hits else None
    text = mc_clean(top["contentFragment"]) if top else ""
    is_reserved_or_reference = bool(top) and ("removed from the code book" in text.lower()
                                               or "reserved" in mc_clean(top["title"]).lower()
                                               or "may be obtained from the planning and zoning commission" in text.lower())
    # A real governing numeric standard would show something like a dimensional figure
    # (e.g. "20,000 square feet") rather than an empty body or an editor's-note redirect.
    looks_like_numeric_standard = bool(re.search(r"\d[\d,]*\s*(square feet|sq\.?\s*ft|acres?)", text.lower()))
    if looks_like_numeric_standard and not is_reserved_or_reference:
        gw_any_governing_numeric_text_found = True

    gw_completeness_rows.append({
        "Search term": term,
        "Top result": mc_clean(top["title"]) if top else "not_available",
        "Node ID": top["nodeId"] if top else "not_available",
        "Finding": ("editor's-note / reference only" if is_reserved_or_reference else
                    "contains a numeric dimensional figure" if looks_like_numeric_standard else
                    "no hits" if not top else "hit found, no dimensional figure detected"),
    })

gw_completeness_df = pd.DataFrame(gw_completeness_rows)
display(gw_completeness_df)

governing_found_str = "YES" if gw_any_governing_numeric_text_found else "NO"
usage = ("primary collection source" if gw_any_governing_numeric_text_found else
         "secondary cross-reference / general-code source only")
supplement = ("none required" if gw_any_governing_numeric_text_found else
              "Town of Greenwich Planning & Zoning Building Zone Regulations page and PDFs "
              "(https://www.greenwichct.gov/442/Building-Zone-Regulations)")

print(f"""
GREENWICH MUNICIPAL COLLECTION DECISION

Municode search capability: PASS
Municode section retrieval capability: PASS
Municode contains full Building Zone Regulations: {governing_found_str}
Municode may be used as: {usage}
Required official supplement: {supplement}
""")
print("Municode is not treated as the sole governing source for Greenwich's Building Zone Regulations.")

,Search term,Top result,Node ID,Finding
0,building zone regulations,ARTICLE 1. - BUILDING ZONE REGULATIONS.,CH6.LAUS_ART1BUZORE,editor's-note / reference only
1,schedule of required open spaces,Sec. 14-7.8. - Twelve-hour parking; metered.,CH14.VETR_ART2TRPARE_S14-7.8TWURPAME,"hit found, no dimensional figure detected"
2,minimum lot size,Sec. 2-31. - Plot plans; specifications.,CH2.AD_ART7PLZOBOAPRU_S2-31PLPLSP,"hit found, no dimensional figure detected"
3,6-205,[Secs. 6-1—6-205. - Reserved.],CH6.LAUS_ART1BUZORE_SS6-1--6-205RE,editor's-note / reference only
4,RA-4,not_available,not_available,no hits
5,R-20,Schedule XA - Permit Parking,CH14.VETR_ART5SC_SCHEDULE_XAPEPA,"hit found, no dimensional figure detected"
6,residential zones,Schedule XXF - Nighttime Parking Prohibited,CH14.VETR_ART5SC_SCHEDULE_XXFNIPAPR,"hit found, no dimensional figure detected"

GREENWICH MUNICIPAL COLLECTION DECISION

Municode search capability: PASS
Municode section retrieval capability: PASS
Municode contains full Building Zone Regulations: NO
Municode may be used as: secondary cross-reference / general-code source only
Required official supplement: Town of Greenwich Planning & Zoning Building Zone Regulations page and PDFs (https://www.greenwichct.gov/442/Building-Zone-Regulations)

Municode is not treated as the sole governing source for Greenwich's Building Zone Regulations.

In [12]:
# --- Step 9: Bridgeport completeness test ---
# Same idea for Bridgeport, with its own term list. Classify into one of the specified
# categories based on what's actually retrieved — not assumed in advance.

BRIDGEPORT_COMPLETENESS_TERMS = [
    "zoning ordinance", "zoning regulations", "zoning districts", "use regulations",
    "minimum lot area", "dimensional requirements", "parking", "two-family", "multifamily",
]

r = mc_resolved["Bridgeport"]
bp_completeness_rows = []
bp_any_governing_numeric_text_found = False

for term in BRIDGEPORT_COMPLETENESS_TERMS:
    _, _, resp = mc_search(r["client_id"], r["state_id"], term, page_size=3, fragment_size=1000)
    hits = resp.json().get("hits", []) if resp.status_code == 200 else []
    top = hits[0] if hits else None
    text = mc_clean(top["contentFragment"]) if top else ""
    title = mc_clean(top["title"]) if top else ""
    is_reserved = bool(top) and "reserved" in title.lower()
    looks_like_numeric_standard = bool(re.search(r"\d[\d,]*\s*(square feet|sq\.?\s*ft|acres?)", text.lower()))
    if looks_like_numeric_standard and not is_reserved:
        bp_any_governing_numeric_text_found = True

    bp_completeness_rows.append({
        "Search term": term,
        "Top result": title if top else "not_available",
        "Node ID": top["nodeId"] if top else "not_available",
        "Finding": ("title marked RESERVED (empty)" if is_reserved else
                    "contains a numeric dimensional figure" if looks_like_numeric_standard else
                    "no hits" if not top else "hit found, no dimensional figure detected"),
    })

bp_completeness_df = pd.DataFrame(bp_completeness_rows)
display(bp_completeness_df)

# Direct, targeted evidence from Step 4/5: Bridgeport's own dedicated zoning title (Title 17)
# was independently retrieved by name and its section body came back empty. That's stronger,
# more specific evidence than scanning top hits for a generic term list, so it anchors the
# classification below rather than being just one row among many.
bp_title17 = next((rec for rec in mc_selected.get("Bridgeport", []) if rec["node_id"] == "TIT17ZORE"), None)
title17_confirmed_empty = bool(bp_title17) and bp_title17["text_len"] == 0
if bp_title17:
    print(f"Bridgeport's dedicated zoning title — \"{bp_title17['section_title']}\" "
          f"(node {bp_title17['node_id']}) — section body text length: {bp_title17['text_len']} "
          f"({'empty' if title17_confirmed_empty else 'non-empty'}).")

if bp_any_governing_numeric_text_found:
    bp_classification = "municode_complete_for_zoning"
elif title17_confirmed_empty:
    bp_classification = "not_suitable_as_primary_zoning_source"
else:
    bp_classification = "municode_accessible_but_zoning_location_unresolved"

print(f"\nBridgeport classification: {bp_classification}")

,Search term,Top result,Node ID,Finding
0,zoning ordinance,3.28.010 - Short title.,TIT3REFI_CH3.28URENZO_3.28.010SHTI,"hit found, no dimensional figure detected"
1,zoning regulations,"Section 9. - Zoning Rules, Regulations, and Di...",CHBR_CH2ELBOCOAP_S9ZORUREDI,"hit found, no dimensional figure detected"
2,zoning districts,"Section 9. - Zoning Rules, Regulations, and Di...",CHBR_CH2ELBOCOAP_S9ZORUREDI,"hit found, no dimensional figure detected"
3,use regulations,Chapter 12.28 - PARK USE REGULATIONS,TIT12STSIPUPL_CH12.28PAUSRE,"hit found, no dimensional figure detected"
4,minimum lot area,"15.12.160 - Minimum space, use and location re...",TIT15BUCO_CH15.12HOCO_15.12.160MISPUSLORE,"hit found, no dimensional figure detected"
5,dimensional requirements,not_available,not_available,no hits
6,parking,Section 8. - Parking.,CHBR_CH14PUFA_S8PA,"hit found, no dimensional figure detected"
7,two-family,8.28.170 - Smoke detection—Where required.,TIT8HESA_CH8.28FIPRRE_8.28.170SMDEHERE,"hit found, no dimensional figure detected"
8,multifamily,not_available,not_available,no hits

Bridgeport's dedicated zoning title — "Title 17 - ZONING (RESERVED)" (node TIT17ZORE) — section body text length: 0 (empty).

Bridgeport classification: not_suitable_as_primary_zoning_source

In [13]:
# --- Visual A: Collection coverage scorecard ---
# Built from the variables computed above, not hand-typed.

def _pf(ok):
    return "PASS" if ok else "FAIL"

gw_resolved_ok = mc_resolved["Greenwich"]["client_id"] is not None
bp_resolved_ok = mc_resolved["Bridgeport"]["client_id"] is not None
gw_search_ok = any(h["Municipality"] == "Greenwich" and h["API call succeeded"] == "Yes" for h in mc_matrix_rows)
bp_search_ok = any(h["Municipality"] == "Bridgeport" and h["API call succeeded"] == "Yes" for h in mc_matrix_rows)
gw_retrieval_ok = any(r["Municipality"] == "Greenwich" and "Yes" in r["Content returned?"] for r in mc_retrieval_rows)
bp_retrieval_ok = any(r["Municipality"] == "Bridgeport" and "Yes" in r["Content returned?"] for r in mc_retrieval_rows)
gw_public_url_ok = all(rec["public_url"].startswith("https://") for rec in mc_selected["Greenwich"])
bp_public_url_ok = all(rec["public_url"].startswith("https://") for rec in mc_selected["Bridgeport"])
gw_zoning_hit = any(h["Municipality"] == "Greenwich" and h["Query"] in ("zoning", "land use", "building zone regulations") and h["Result count"] > 0 for h in mc_matrix_rows)
bp_zoning_hit = any(h["Municipality"] == "Bridgeport" and h["Query"] in ("zoning", "land use", "building zone regulations") and h["Result count"] > 0 for h in mc_matrix_rows)

print("MUNICODE COLLECTION VALIDATION SCORECARD\n")
print(f"{'':30s}{'Greenwich, CT':<22}{'Bridgeport, CT'}")
print(f"{'Municipality lookup':30s}{_pf(gw_resolved_ok):<22}{_pf(bp_resolved_ok)}")
print(f"{'API search':30s}{_pf(gw_search_ok):<22}{_pf(bp_search_ok)}")
print(f"{'Section retrieval':30s}{_pf(gw_retrieval_ok):<22}{_pf(bp_retrieval_ok)}")
print(f"{'Public URL generated':30s}{_pf(gw_public_url_ok):<22}{_pf(bp_public_url_ok)}")
print(f"{'Public-page reconciliation':30s}{'PARTIAL (static-fetch limit)':<22}{'PARTIAL (static-fetch limit)'}")
print(f"{'Zoning-relevant hit found':30s}{_pf(gw_zoning_hit):<22}{_pf(bp_zoning_hit)}")
print(f"{'Full zoning source?':30s}{governing_found_str:<22}{'YES' if bp_classification=='municode_complete_for_zoning' else 'NO'}")
print(f"{'External-AI-ready text?':30s}{'PARTIAL (cross-ref only)':<22}{'PARTIAL' if bp_classification!='municode_complete_for_zoning' else 'YES'}")

MUNICODE COLLECTION VALIDATION SCORECARD

                              Greenwich, CT         Bridgeport, CT
Municipality lookup           PASS                  PASS
API search                    PASS                  PASS
Section retrieval             PASS                  PASS
Public URL generated          PASS                  PASS
Public-page reconciliation    PARTIAL (static-fetch limit)PARTIAL (static-fetch limit)
Zoning-relevant hit found     PASS                  PASS
Full zoning source?           NO                    NO
External-AI-ready text?       PARTIAL (cross-ref only)PARTIAL

In [14]:
# --- Visual B: Source lineage diagrams ---
# Built from the actual retrieved node for each municipality's "zoning/land-use section" pick.

def lineage_diagram(name):
    r = mc_resolved[name]
    zoning_rec = next((rec for rec in mc_selected[name] if rec["category"] == "zoning/land-use section"), None)
    node_id = zoning_rec["node_id"] if zoning_rec else "not_available"
    final_step = ("Official PDF verification required (see completeness decision above)"
                  if name == "Greenwich" or bp_classification != "municode_complete_for_zoning"
                  else "Municode treated as sufficient primary source")
    print(f"{name}, CT\n")
    print("Municipality + State")
    print("        |")
    print(f"Municode ClientID ({r['client_id']})")
    print("        |")
    print(f'Municode search query ("{zoning_rec["search_query"] if zoning_rec else "not_available"}")')
    print("        |")
    print(f"Returned node ID ({node_id})")
    print("        |")
    print("API section-text response")
    print("        |")
    print(f"Public Municode URL ({zoning_rec['public_url'] if zoning_rec else 'not_available'})")
    print("        |")
    print("Candidate evidence record (status: candidate_text_found_needs_human_review)")
    print("        |")
    print("External AI relevance review")
    print("        |")
    print(f"{final_step}")
    print()

lineage_diagram("Greenwich")
lineage_diagram("Bridgeport")

Greenwich, CT

Municipality + State
        |
Municode ClientID (8693)
        |
Municode search query ("building zone regulations")
        |
Returned node ID (CH6.LAUS_ART1BUZORE)
        |
API section-text response
        |
Public Municode URL (https://library.municode.com/ct/greenwich/codes/code_of_ordinances?nodeId=CH6.LAUS_ART1BUZORE)
        |
Candidate evidence record (status: candidate_text_found_needs_human_review)
        |
External AI relevance review
        |
Official PDF verification required (see completeness decision above)

Bridgeport, CT

Municipality + State
        |
Municode ClientID (12889)
        |
Municode search query ("Title 17 Zoning Reserved")
        |
Returned node ID (TIT17ZORE)
        |
API section-text response
        |
Public Municode URL (https://library.municode.com/ct/bridgeport/codes/code_of_ordinances?nodeId=TIT17ZORE)
        |
Candidate evidence record (status: candidate_text_found_needs_human_review)
        |
External AI relevance review
        |
Official PDF verification required (see completeness decision above)

In [15]:
# --- Visual D: Sample source-evidence packet (what gets handed to an external AI) ---
# One JSON object per municipality, built entirely from retrieved fields above — nothing
# in this packet is typed in by hand.
import json

mc_evidence_packets = {}
for name in ("Greenwich", "Bridgeport"):
    rec = next((x for x in mc_selected[name] if x["category"] == "zoning/land-use section"), None)
    r = mc_resolved[name]
    packet = {
        "municipality": name,
        "state": "CT",
        "publisher": "Municode",
        "collection_adapter": "municode_api",
        "retrieved_at_utc": rec["retrieved_at"] if rec else "not_available",
        "client_id": r["client_id"],
        "search_query": rec["search_query"] if rec else "not_available",
        "section_title": rec["section_title"] if rec else "not_available",
        "chapter_path": rec["chapter_path"] if rec else "not_available",
        "node_id": rec["node_id"] if rec else "not_available",
        "public_source_url": rec["public_url"] if rec else "not_available",
        "literal_section_text": rec["literal_text"] if rec else "not_available",
        "section_text_sha256": rec["text_sha256"] if rec else "not_available",
        "evidence_status": "candidate_text_found_needs_human_review",
        "limitations": ("Search result relevance and governing applicability remain unverified. "
                        "Public-page reconciliation is limited to URL reachability because "
                        "library.municode.com renders section text client-side."),
    }
    mc_evidence_packets[name] = packet
    print(f"=== {name} evidence packet ===")
    print(json.dumps(packet, indent=2)[:1500])
    print()

=== Greenwich evidence packet ===
{
  "municipality": "Greenwich",
  "state": "CT",
  "publisher": "Municode",
  "collection_adapter": "municode_api",
  "retrieved_at_utc": "2026-10-02T15:07:05.664396+00:00",
  "client_id": 8693,
  "search_query": "building zone regulations",
  "section_title": "ARTICLE 1. - BUILDING ZONE REGULATIONS.",
  "chapter_path": "Greenwich, Connecticut - Code of Ordinances > CHAPTER 6. LAND USE",
  "node_id": "CH6.LAUS_ART1BUZORE",
  "public_source_url": "https://library.municode.com/ct/greenwich/codes/code_of_ordinances?nodeId=CH6.LAUS_ART1BUZORE",
  "literal_section_text": "Footnotes: --- (1) --- Editor's note\u2014 Article I, Building Zone Regulations, adopted 2-1-26, revised 9-3-47 and amended, was removed from the Code book pursuant to a request from the Town of Greenwich. The current Building Zone Regulations may be obtained from the Planning and Zoning Commission.",
  "section_text_sha256": "5321c6b658f0804b74ba45d894dfc01645bdcaa0005b9acc96c0a0db6737b86e",
  "evidence_status": "candidate_text_found_needs_human_review",
  "limitations": "Search result relevance and governing applicability remain unverified. Public-page reconciliation is limited to URL reachability because library.municode.com renders section text client-side."
}

=== Bridgeport evidence packet ===
{
  "municipality": "Bridgeport",
  "state": "CT",
  "publisher": "Municode",
  "collection_adapter": "municode_api",
  "retrieved_at_utc": "2026-10-02T15:07:06.371618+00:00",
  "client_id": 12889,
  "search_query": "Title 17 Zoning Reserved",
  "section_title": "Title 17 - ZONING (RESERVED)",
  "chapter_path": "Bridgeport, Connecticut - Code of Ordinances",
  "node_id": "TIT17ZORE",
  "public_source_url": "https://library.municode.com/ct/bridgeport/codes/code_of_ordinances?nodeId=TIT17ZORE",
  "literal_section_text": "",
  "section_text_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "evidence_status": "candidate_text_found_needs_human_review",
  "limitations": "Search result relevance and governing applicability remain unverified. Public-page reconciliation is limited to URL reachability because library.municode.com renders section text client-side."
}

In [16]:
# --- Final conclusion ---
mc_overall_validated = gw_resolved_ok and bp_resolved_ok and gw_search_ok and bp_search_ok and gw_retrieval_ok and bp_retrieval_ok
mc_overall_label = "municode_api_collection_validated" if mc_overall_validated else "municode_api_retrieval_partial"

gw_zoning_classification = "municode_complete_for_zoning" if gw_any_governing_numeric_text_found else "municode_general_code_only"

print(f"Overall collection-layer validation: {mc_overall_label}")
print(f"Greenwich zoning-completeness classification: {gw_zoning_classification}")
print(f"Bridgeport zoning-completeness classification: {bp_classification}")
print()
print("Greenwich: The Municode API can retrieve and cite searchable municipal-code sections "
      "(resolution, search, and section-text retrieval all PASS), but it is not a complete "
      "substitute for the Town's official Building Zone Regulations and schedules — the "
      "Building Zone Regulations article in Municode is an editor's-note placeholder, not "
      "governing text.")
print()
print("Bridgeport: The Municode API can retrieve and cite general code-of-ordinances text "
      "(resolution, search, and section-text retrieval all PASS), but its dedicated zoning "
      f"title (Title 17 - ZONING) came back empty/RESERVED in this test, so the classification "
      f"is {bp_classification} — Municode is not demonstrated here as a source of Bridgeport's "
      "substantive zoning district/dimensional rules.")

Overall collection-layer validation: municode_api_collection_validated
Greenwich zoning-completeness classification: municode_general_code_only
Bridgeport zoning-completeness classification: not_suitable_as_primary_zoning_source

Greenwich: The Municode API can retrieve and cite searchable municipal-code sections (resolution, search, and section-text retrieval all PASS), but it is not a complete substitute for the Town's official Building Zone Regulations and schedules — the Building Zone Regulations article in Municode is an editor's-note placeholder, not governing text.

Bridgeport: The Municode API can retrieve and cite general code-of-ordinances text (resolution, search, and section-text retrieval all PASS), but its dedicated zoning title (Title 17 - ZONING) came back empty/RESERVED in this test, so the classification is not_suitable_as_primary_zoning_source — Municode is not demonstrated here as a source of Bridgeport's substantive zoning district/dimensional rules.